# Site settings
title: A blog about datascience and python & R programming
description: A blog about datasience and python & R programming
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alejandro Mañas
user_description: In the last ten years I have worked as a Business Intelligence consultant for companies in different sectors of activity (healthcare, hotels, beverage bottler, footwear manufacturing, legal assistance services). Some time ago, I decided to give my career a boost by delving into analytical skills. I discovered the potential of data analysis-oriented programming languages (R & Python) and the great possibilities of using machine learning techniques
user_title: Data scientist & Business Intelligence Consultant
email: alejandromanas@outlook.com
twitter_username: alejandromanas5
github_username:  alejandromanas

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

#theme: jekyll-theme-cayman